### ISSUE TITLE
Compiled renderer does not throw on ambiguous views

### ISSUE THREAD

**Issue by jnferner** [StubbleOrg/Stubble#81] opened 2019-11-29 12:15 UTC
When using the setting `SetIgnoreCaseOnKeyLookup(true)`, the behavior when passing an ambiguous view. 
On the template 
`"{{name}}"` 
with the view
 ```c#
new { Name = "foo", name = "bar" }
```
the regular renderer throws an `StubbleException`, while the compiled one simply uses the first property, resulting in `"foo"`

**Comment by Romanx** [comment] 2019-11-30 14:28
Hey there,

Thanks for opening this issue. You're right this is definately an oversight and I get an argument exception on the default renderer since we're not handling this case gracefully.

I've added a new exception type `StubbleAmbigousMatchException` which will be thrown when this happens, on Compile for the compilation renderer and on Render for the standard renderer.

I'll get this merged shortly into master and after i've looked at your other issue i'll get a release out. Thanks for your clear reproduction cases

**Comment by Romanx** [comment] 2019-12-01 21:52
@jnferner Thanks very much for reporting this. It has been fixed in release 1.6.3 and has now been released on nuget.

Please let us know if you have any other issues.

**Closed by Romanx** 2019-12-01 21:52 UTC
Labels: bug
